#!/bin/bash
# 2. В параметрах при запуске скрипта передаются 
# три целых числа. Вывести максимальное из них.

if [ $# -eq 3 ]; then
    if [ $1 -ge $2 ] && [ $1 -ge $3 ]; then
        echo "$1"
    elif [ $2 -ge $1 ] && [ $2 -ge $3 ]; then
        echo "$2"
    else
        echo "$3"
    fi
else
    echo "There must be 3 integers!"
fi
